import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PDF Chat",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black text-white`}>
        <div className="relative min-h-screen overflow-hidden">
          <main className="mx-auto w-screen max-w-[900px]">{children}</main>
          <div className="absolute -top-[400px] left-1/2 -z-50 h-[800px] w-[800px] -translate-x-1/2 rounded-full bg-primary opacity-60 blur-[200px]"></div>
        </div>
      </body>
    </html>
  );
}
